import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// fonts
import '../../public/fonts/index.css';
import { SettingsProvider, ThemeSettings } from '@/components/settings';
import ThemeProvider from '@/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className="w-full ">
      <body className="w-full h-full flex flex-col relative overflow-scroll">
        <SettingsProvider>
          <ThemeProvider>
            <ThemeSettings>
              {children}
              {/* <Toaster
                                        richColors
                                        offset={90}
                                        position="bottom-center"
                                        dir="rtl"
                                        style={{ fontFamily: 'IRANSans' }}
                                   /> */}
            </ThemeSettings>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
